# Generated by Django 5.2.3 on 2025-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='destination',
            new_name='end_location',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='origin',
            new_name='start_location',
        ),
    ]
