# Generated by Django 5.2.3 on 2025-06-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_remove_booking_stop_booking_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stop',
        ),
        migrations.AddField(
            model_name='booking',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rides.stop'),
        ),
    ]
