# Generated by Django 5.2.3 on 2025-06-14 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_booking_stop_booking_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rides.stop'),
            preserve_default=False,
        ),
    ]
