# Generated by Django 5.2.3 on 2025-08-18 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_ride_status_booking_status_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('driver_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_type', models.CharField(choices=[('ride_payment', 'Ride Payment'), ('refund', 'Refund'), ('top_up', 'Top Up')], default='ride_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rides.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
