# Generated by Django 5.2.3 on 2025-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_stop_rename_destination_ride_end_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='stops',
        ),
        migrations.AddField(
            model_name='ride',
            name='stops',
            field=models.ManyToManyField(to='rides.stop'),
        ),
    ]
