# Generated by Django 5.2.3 on 2025-06-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_ride_stops_ride_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stop',
        ),
        migrations.AddField(
            model_name='booking',
            name='stop',
            field=models.ManyToManyField(to='rides.stop'),
        ),
    ]
