# Generated by Django 5.2.4 on 2025-08-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_update_bus_stops'),
        ('rides', '0007_bus_busschedule'),
    ]

    operations = [
    ]
