# Generated by Django 4.2.23 on 2026-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_stop_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='stop',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
