# Generated by Django 4.2.23 on 2026-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_stop_route_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
